import type { Prisma } from "@prisma/client";

export async function exportPlatformBackup(client: Prisma.TransactionClient) {
  const [
    users,
    households,
    memberships,
    entitlements,
    auditEvents,
    categoryGroups,
    categories,
    accounts,
    accountPockets,
    incomeSources,
    incomeAllocations,
    plannedTransfers,
    budgetItems,
    exchangeRates,
    statementImports,
    actualTransactions,
    actualAllocations,
    allocationRules,
    transferMatches,
  ] = await Promise.all([
    client.user.findMany({
      select: {
        id: true,
        email: true,
        passwordHash: true,
        displayName: true,
        instanceAdmin: true,
        emailVerifiedAt: true,
        active: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    client.household.findMany(),
    client.householdMember.findMany(),
    client.tierEntitlement.findMany(),
    client.auditEvent.findMany({ orderBy: { createdAt: "asc" } }),
    client.categoryGroup.findMany(),
    client.category.findMany(),
    client.account.findMany(),
    client.accountPocket.findMany(),
    client.incomeSource.findMany(),
    client.incomeAllocation.findMany(),
    client.plannedAccountTransfer.findMany(),
    client.budgetItem.findMany(),
    client.exchangeRate.findMany(),
    client.statementImport.findMany(),
    client.actualTransaction.findMany(),
    client.actualTransactionAllocation.findMany(),
    client.transactionAllocationRule.findMany(),
    client.transactionTransferMatch.findMany(),
  ]);

  return {
    format: "tl-finance-platform-backup",
    version: 1,
    exportedAt: new Date().toISOString(),
    excludes: ["sessions", "emailVerificationTokens", "passwordResetTokens"],
    users,
    households,
    memberships,
    entitlements,
    auditEvents,
    categoryGroups,
    categories,
    accounts,
    accountPockets,
    incomeSources,
    incomeAllocations,
    plannedTransfers,
    budgetItems,
    exchangeRates,
    statementImports,
    actualTransactions,
    actualAllocations,
    allocationRules,
    transferMatches,
  };
}
